Repository aws-controllers-k8s/recyclebin-controller, pull requests merged in 2024-08, with the labels that each got.

#2 Fill missing fields in metadata.yaml
  metadata.yaml
Labels: approved

#4 update olmconfig with description and examples
  olm/olmconfig.yaml
Labels: needs-ok-to-test

#5 Introduce `Rule` resource
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/enums.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/rule.go
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/recyclebin.services.k8s.aws_rules.yaml
  config/crd/kustomization.yaml
  config/iam/recommended-inline-policy
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/recyclebin.services.k8s.aws_rules.yaml
  helm/templates/_helpers.tpl
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  helm/values.yaml
  pkg/resource/rule/delta.go
  pkg/resource/rule/descriptor.go
  pkg/resource/rule/hooks.go
  pkg/resource/rule/identifiers.go
  pkg/resource/rule/manager.go
  pkg/resource/rule/manager_factory.go
  pkg/resource/rule/references.go
  pkg/resource/rule/resource.go
  pkg/resource/rule/sdk.go
  pkg/resource/rule/tags.go
  pkg/tags/sync.go
  rule.yaml
  templates/.gitkeep
  templates/hooks/rule/sdk_read_one_post_set_output.go.tpl
  templates/hooks/rule/sdk_update_pre_build_request.go.tpl
  test/e2e/__init__.py
  test/e2e/conftest.py
  test/e2e/resources/.gitkeep
  test/e2e/resources/rule.yaml
  test/e2e/tests/helper.py
  test/e2e/tests/test_rule.py
Labels: approved, lgtm

#6 Release artifacts for release `v0.0.1`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm
